---
- name: Install MySQL package
  yum: pkg={{item}} state=present
  with_items:
    - mysql-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create MySQL configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start mysql service
  service: name=mysqld state=started enabled=true

